resume: #ckpt/model_best.pth
save_ftt_dir: ./ckpt_ftt/
log_dir: tensorboard/
gpu: true
n_gpu: 2
metrics:
  - _target_: srcs.model.metric.accuracy
  - _target_: srcs.model.metric.precision
  - _target_: srcs.model.metric.recall
  - _target_: srcs.model.metric.f1
  - _target_: srcs.model.metric.f1_macro

defaults:
  - _self_
  - data: aidao
  - model: MultimodalModel
  - hparams: bebryata_model
  - status: train
  - hydra/run/dir: job_timestamp
  - override hydra/job_logging : custom