defaults:
  - _self_
  - data: time_series_custom
  - model: patchtst_custom
  - hparams: training_params
  - override hydra/job_logging: custom

n_gpu: 20
output_dir: "outputs/patchtst_custom/${now:%Y-%m-%d_%H-%M-%S}"