# @package _global_
name: MultimodalModel
arch:
  _target_: srcs.model.model.get_model
  text_model_name: ${tokenizer.model_name} 

loss:
  _target_: torch.nn.BCEWithLogitsLoss

optimizer:
  _target_: torch.optim.AdamW
  lr: ${learning_rate}
  weight_decay: ${weight_decay}
  betas: [0.9, 0.999]
  eps: 1e-8
lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.2
  patience: 3
  min_lr: 1e-6