name: PatchTST_Custom
arch:
  _target_: src.model.patchtst.model.Model
  configs:
    enc_in: 45
    seq_len: 160
    pred_len: 8
    patch_len: 16
    stride: 8
    e_layers: 3
    n_heads: 4
    d_model: 16
    d_ff: 128
    dropout: 0.1
    fc_dropout: 0.1
    head_dropout: 0.0
    individual: false
    revin: true
    affine: true
    subtract_last: false
    decomposition: false
    kernel_size: 25
    padding_patch: null
    channel_mixing: true
    
target_channel_idx: 0

loss:
  _target_: torch.nn.MSELoss

optimizer:
  _target_: torch.optim.AdamW
  lr: ${hparams.learning_rate}
  weight_decay: ${hparams.weight_decay}

lr_scheduler:
  _target_: transformers.get_cosine_schedule_with_warmup
  # mode: min
  # factor: 0.2
  # patience: 3