name: PatchTST_Custom
arch:
  _target_: src.model.patchtst.model.Model
  configs:
    # --- Параметры данных ---
    enc_in: 651
    seq_len: 160
    pred_len: 8
    patch_len: 16
    stride: 8
    e_layers: 4
    n_heads: 8
    d_model: 32
    d_ff: 128
    dropout: 0.2
    fc_dropout: 0.1
    head_dropout: 0.0
    individual: false
    revin: true
    affine: true
    subtract_last: false
    decomposition: true
    kernel_size: 49
    padding_patch: null

target_channel_idx: 0

loss:
  _target_: torch.nn.MSELoss

optimizer:
  _target_: torch.optim.AdamW
  lr: ${hparams.learning_rate}
  weight_decay: ${hparams.weight_decay}

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.2
  patience: 3